# Generated by Django 2.2.5 on 2019-10-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=20)),
                ('score', models.CharField(max_length=20)),
            ],
        ),
    ]
