# Generated by Django 2.2.5 on 2019-10-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('sage', models.IntegerField()),
                ('sscore', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='web',
            name='age',
            field=models.IntegerField(),
        ),
    ]
